USE `travel-itinerary`;

INSERT INTO `travel-itinerary`.locationcode VALUES
-- International
('ATL', 'Atlanta'),
('PEK', 'Beijing'),
('LHR', 'London'),
('HND', 'Tokyo'),
('DXB', 'Dubai'),
('LAX', 'Los Angeles'),
('CDG', 'Paris'),
('DFW', 'Dallas/Fort Worth'),
('FRA', 'Frankfurt'),
('HKG', 'Hong Kong'),
('DEN', 'Denver'),
('ORD', 'Chicago'),
('AMS', 'Amsterdam'),
('MAD', 'Madrid'),
('BKK', 'Bangkok'),
('JFK', 'New York'),
('SIN', 'Singapore'),
('CAN', 'Guangzhou'),
('LAS', 'Las Vegas'),
('PVG', 'Shanghai'),
('SFO', 'San Francisco'),
('PHX', 'Phoenix'),
('IAH', 'Houston'),
('CLT', 'Charlotte'),
('MIA', 'Miami'),
('MUC', 'Munich'),
('KUL', 'Kuala Lumpur'),
('FCO', 'Rome'),
('IST', 'Istanbul'),
('SYD', 'Sydney'),
('MCO', 'Orlando'),
('ICN', 'Seoul'),
('DEL', 'New Delhi'),
('BCN', 'Barcelona'),
('LGW', 'London'),
('EWR', 'Newark'),
('YYZ', 'Toronto'),
('SHA', 'Shanghai'),
('MSP', 'Minneapolis'),
('SEA', 'Seattle'),
('DTW', 'Detroit'),
('PHL', 'Philadelphia'),
('BOM', 'Mumbai'),
('GRU', 'São Paulo'),
('MNL', 'Manila'),
('CTU', 'Chengdu'),
('BOS', 'Boston'),
('SZX', 'Shenzhen'),
('MEL', 'Melbourne'),
('NRT', 'Tokyo'),
('ORY', 'Paris'),
('MEX', 'Mexico City'),
('DME', 'Moscow'),
('ZRH', 'Zurich'),
('VIE', 'Vienna'),
('CPH', 'Copenhagen'),
('OSL', 'Oslo'),
('ARN', 'Stockholm'),
('HEL', 'Helsinki'),
('BRU', 'Brussels'),
('DUB', 'Dublin'),
('LIS', 'Lisbon'),
('PRG', 'Prague'),
('WAW', 'Warsaw'),
('BUD', 'Budapest'),
('ATH', 'Athens'),
('GVA', 'Geneva'),
('LYS', 'Lyon'),
('NCE', 'Nice'),
('HAM', 'Hamburg'),
('DUS', 'Düsseldorf'),
('BER', 'Berlin'),
('STR', 'Stuttgart'),
('MAN', 'Manchester'),
('BHX', 'Birmingham'),
('EDI', 'Edinburgh'),
('GLA', 'Glasgow'),
('CPT', 'Cape Town'),
('JNB', 'Johannesburg'),
('LOS', 'Lagos'),
('CAI', 'Cairo'),
('NBO', 'Nairobi'),
('ADD', 'Addis Ababa'),
('DAR', 'Dar es Salaam'),
('CMN', 'Casablanca'),
('ALG', 'Algiers'),
('TUN', 'Tunis'),
('ACC', 'Accra'),
('ABV', 'Abuja'),
('KRT', 'Khartoum'),
('DKR', 'Dakar'),
('LAD', 'Luanda'),
('FIH', 'Kinshasa'),
('BGF', 'Bangui'),
('NDJ', 'N\'Djamena'),
('GOM', 'Goma'),
('FKI', 'Kisangani'),
('FBM', 'Lubumbashi'),
('BZV', 'Brazzaville'),
('DIL', 'Dili'),
('BPN', 'Balikpapan'),
('BTJ', 'Banda Aceh'),
('KJT', 'Bandung'),
('BTH', 'Batam'),
('BQN', 'Aguadilla'),
('SJU', 'San Juan'),
('SBH', 'Saint Jean'),
('KIV', 'Chişinău'),
('ARW', 'Arad'),
('BCM', 'Bacau'),
('BAY', 'Baia Mare'),
('GHV', 'Brașov'),
('RUN', 'Saint-Denis'),
('KGL', 'Kigali'),
('SEZ', 'Victoria'),
('ORK', 'Cork'),
('KIR', 'Kerry'),
('NOC', 'Knock'),
('SNN', 'Shannon'),

-- North America
('LGA', 'New York'),
('FLL', 'Fort Lauderdale'),
('BWI', 'Baltimore'),
('SLC', 'Salt Lake City'),
('DCA', 'Washington, D.C.'),
('SAN', 'San Diego'),
('TPA', 'Tampa'),
('PDX', 'Portland'),
('HNL', 'Honolulu'),
('STL', 'St. Louis'),
('BNA', 'Nashville'),
('AUS', 'Austin'),
('MCI', 'Kansas City'),
('RDU', 'Raleigh/Durham'),
('SJC', 'San Jose'),
('CLE', 'Cleveland'),
('SMF', 'Sacramento'),
('IND', 'Indianapolis'),
('PIT', 'Pittsburgh'),
('CMH', 'Columbus'),
('MKE', 'Milwaukee'),
('CVG', 'Cincinnati'),
('ORF', 'Norfolk'),
('JAX', 'Jacksonville'),
('MEM', 'Memphis'),
('RIC', 'Richmond'),
('OKC', 'Oklahoma City'),
('OMA', 'Omaha'),
('TUL', 'Tulsa'),
('BUR', 'Burbank'),
('ONT', 'Ontario'),
('SNA', 'Santa Ana'),
('BOI', 'Boise'),
('ABQ', 'Albuquerque'),
('ANC', 'Anchorage'),
('BUF', 'Buffalo'),
('ROC', 'Rochester'),
('SYR', 'Syracuse'),
('ALB', 'Albany'),
('BDL', 'Hartford'),
('PWM', 'Portland'),
('BTV', 'Burlington'),
('GSO', 'Greensboro'),
('CHS', 'Charleston'),
('SAV', 'Savannah'),
('PNS', 'Pensacola'),
('TLH', 'Tallahassee'),
('ECP', 'Panama City'),
('GPT', 'Gulfport'),
('JAN', 'Jackson'),
('BTR', 'Baton Rouge'),
('LFT', 'Lafayette'),
('SHV', 'Shreveport'),
('LIT', 'Little Rock'),
('XNA', 'Fayetteville'),
('FSM', 'Fort Smith'),
('SGF', 'Springfield'),
('COU', 'Columbia'),
('CID', 'Cedar Rapids'),
('DSM', 'Des Moines'),
('MLI', 'Moline'),
('PIA', 'Peoria'),
('EVV', 'Evansville'),
('SDF', 'Louisville'),
('LEX', 'Lexington'),
('HSV', 'Huntsville'),
('MOB', 'Mobile'),
('PVD', 'Providence'),
('MHT', 'Manchester'),
('BGR', 'Bangor'),
('ACY', 'Atlantic City'),
('AVP', 'Scranton'),
('ABE', 'Allentown'),
('MDT', 'Harrisburg'),
('ILM', 'Wilmington'),
('MYR', 'Myrtle Beach'),

-- Michigan Airports
('GRR', 'Grand Rapids'),
('FNT', 'Flint'),
('LAN', 'Lansing'),
('AZO', 'Kalamazoo'),
('TVC', 'Traverse City'),
('MQT', 'Marquette'),
('CIU', 'Sault Ste. Marie'),
('MBS', 'Saginaw'),
('ESC', 'Escanaba'),
('PLN', 'Pellston'),
('APN', 'Alpena'),
('GLR', 'Gaylord'),
('IMT', 'Iron Mountain'),
('IWD', 'Ironwood'),
('SAW', 'Marquette County'),

-- Texas Airports
('HOU', 'Houston Hobby'),
('DAL', 'Dallas Love Field'),
('MAF', 'Midland'),
('LBB', 'Lubbock'),
('HRL', 'Harlingen'),
('CRP', 'Corpus Christi'),
('BRO', 'Brownsville'),
('MFE', 'McAllen'),
('TYR', 'Tyler'),
('ACT', 'Waco'),
('SJT', 'San Angelo'),
('CLL', 'College Station'),
('AMA', 'Amarillo'),
('LRD', 'Laredo'),
('VCT', 'Victoria'),
('GGG', 'Longview'),
('ABI', 'Abilene'),
('BPT', 'Beaumont'),
('TXK', 'Texarkana'),
('PSX', 'Palacios'),

-- canadian airports
('YVR', 'Vancouver'),
('YUL', 'Montreal'),
('YYC', 'Calgary'),
('YEG', 'Edmonton'),
('YOW', 'Ottawa'),
('YWG', 'Winnipeg'),
('YXE', 'Saskatoon'),
('YQR', 'Regina'),
('YHZ', 'Halifax'),
('YQB', 'Quebec City'),
('YMM', 'Fort McMurray'),
('YXS', 'Prince George'),
('YXY', 'Whitehorse'),
('YFB', 'Iqaluit'),
('YQX', 'Gander'),
('YQM', 'Moncton'),
('YSJ', 'Saint John'),
('YYT', 'St. John\'s'),
('YTZ', 'Toronto City'),
('YXX', 'Abbotsford'),
('YHM', 'Hamilton'),
('YKF', 'Kitchener'),
('YXU', 'London'),
('YAM', 'Sault Ste. Marie'),
('YQT', 'Thunder Bay'),
('YQG', 'Windsor'),
('YCD', 'Nanaimo'),
('YQQ', 'Comox'),
('YBL', 'Campbell River'),
('YPR', 'Prince Rupert'),
('YKA', 'Kamloops'),
('YLW', 'Kelowna'),
('YCG', 'Castlegar'),
('YXC', 'Cranbrook'),
('YQL', 'Lethbridge'),
('YQF', 'Red Deer'),
('YPA', 'Prince Albert'),
('YBR', 'Brandon'),
('YPG', 'Portage la Prairie'),
('YQK', 'Kenora'),
('YHD', 'Dryden'),
('YTL', 'Big Trout Lake'),
('YXL', 'Sioux Lookout'),
('YPL', 'Pickle Lake'),
('YPM', 'Pikangikum'),
('YNO', 'North Spirit Lake'),
('YWP', 'Webequie'),
('YZR', 'Sarnia'),
('YOS', 'Owen Sound'),
('YHS', 'Sechelt'),
('YAZ', 'Tofino'),
('YWS', 'Whistler'),
('YWL', 'Williams Lake');
